apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traffic-ingress
  namespace: traffic-system
spec:
  rules:
    - host: traffic.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traffic-platform
                port:
                  number: 8000
